language: ruby
rvm:
  - 2.1.1
install: bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - touch config/database.yml
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rspec
  - bundle exec teaspoon