default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ticket_admin
  password: ticket123
  host: 127.0.0.1

development:
  <<: *default
  database: ticket_app_dev

test:
  <<: *default
  database: ticket_app_testing

production:
  <<: *default
  database: ticket_app_prod
  username: messanger
  password: <%= ENV['MESSANGER_DATABASE_PASSWORD'] %>
